---

- name: Installing mod-gearman-module
  apt:
    name:
      - mod-gearman-module
      - libgearman7
    state: present
    update_cache: yes
  # mod-gearman-module from console repository is buggy
  # 1. chown: invalid user: 'naemon:naemon'
  # 2. cp: cannot stat '/usr/share/doc/mod-gearman-module/examples/module.conf.gz': No such file or directory
  ignore_errors: yes

- name: Creating required mod-gearman directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ cmk_site_name }}"
    group: "{{ cmk_site_name }}"
    mode: 0755
  with_items:
    - /opt/omd/sites/{{ cmk_site_name }}/etc/mod-gearman
    - /opt/omd/sites/{{ cmk_site_name }}/var/log/gearman

- name: Writing nagios mod-gearman.cfg
  copy:
    dest: /opt/omd/sites/{{ cmk_site_name }}/etc/mod-gearman/mod-gearman.cfg
    owner: "{{ cmk_site_name }}"
    group: "{{ cmk_site_name }}"
    content: |
      #
      # Mod-Gearman NEB Module
      #

      event_broker_options=-1
      broker_module=/usr/lib/mod_gearman/mod_gearman_nagios3.o config=/opt/omd/sites/{{ cmk_site_name }}/etc/mod-gearman/server.cfg

- name: Writing mod-gearman secretfile
  copy:
    dest: /opt/omd/sites/{{ cmk_site_name }}/etc/mod-gearman/secret.key
    owner: "{{ cmk_site_name }}"
    group: "{{ cmk_site_name }}"
    content: |
      {{ cmk_mod_gearman_secret }}

- name: Linking mod-gearman.cfg to nagios.d
  file:
    src: /opt/omd/sites/{{ cmk_site_name }}/etc/mod-gearman/mod-gearman.cfg
    dest: /opt/omd/sites/{{ cmk_site_name }}/etc/nagios/nagios.d/mod-gearman.cfg
    owner: "{{ cmk_site_name }}"
    group: "{{ cmk_site_name }}"
    state: link

- name: Writing mod-gearman server.cfg
  template:
    src: mod-gearman_server.cfg.j2
    dest: /opt/omd/sites/{{ cmk_site_name }}/etc/mod-gearman/server.cfg
    owner: "{{ cmk_site_name }}"
    group: "{{ cmk_site_name }}"