---

- block:
    - name: Grafana | Debian | Importing Grafana key for the grafana debian repository
      apt_key:
        url: "https://packages.grafana.com/gpg.key"

    - name: Grafana | Debian | Adding Grafana repository
      apt_repository:
        filename: grafana_stable
        repo: "deb http://packages.grafana.com/oss/deb stable main"
        update_cache: no
        state: present

    - name: Grafana | Debian | Installing
      apt:
        name: grafana
        state: present
        update_cache: yes
      notify:
        - Handler | Restart Grafana

    - name: Grafana | Debian | Configuring apache2 for grafana
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - { src: grafana_apache2.conf.j2, dest: /etc/apache2/conf-available/grafana.conf }
      notify:
        - Handler | Restart Apache2

    - name: Grafana | Debian | Symlinking grafana apache2 configuration
      file:
        src: /etc/apache2/conf-available/grafana.conf
        dest: /etc/apache2/conf-enabled/grafana.conf
        force: yes
        owner: root
        group: root
        state: link
      notify:
        - Handler | Restart Apache2
  when: ansible_os_family == "Debian"

- block:
    - name: Grafana | RedHat | Importing grafana gpg key
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.grafana.com/gpg.key

    - name: Grafana | RedHat | Adding grafana oss repo
      blockinfile:
        dest: /etc/yum.repos.d/grafana.repo
        block: |
          [grafana]
          name=grafana
          baseurl=https://packages.grafana.com/oss/rpm
          repo_gpgcheck=1
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.grafana.com/gpg.key
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
        create: true
        owner: root
        group: root
        mode: 0644

    - name: Grafana | RedHat | Installing
      dnf:
        name: grafana
        state: present
        update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Grafana | Replacing Unicode character for ini_file module
  replace:
    path: /etc/grafana/grafana.ini
    regexp: '’'
    replace: "'"

- name: Grafana | Configuring
  ini_file:
    path: /etc/grafana/grafana.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    owner: root
    group: grafana
    mode: 0640
    #backup: yes
  with_items: "{{ cmk_grafana_settings }}"
  notify:
    - Handler | Restart Grafana

- name: Grafana | Configuring | Creating the grafana provisioning folder
  file:
    path: /etc/grafana/provisioning/datasources/
    state: directory
    owner: root
    group: root
    mode: 0755
  when: cmk_enable_dual_graphing

- name: Grafana | Configuring | Provisioning database nagflux
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: grafana_datasource.yml.j2, dest: /etc/grafana/provisioning/datasources/influxdb-nagflux.yml }
  notify:
    - Handler | Restart Grafana
  when: cmk_enable_dual_graphing
