---

- block:
    - name: InfluxDB | Debian | Adding gpg key for influxdb repo
      apt_key:
        url: https://repos.influxdata.com/influxdb.key
        state: present

    - name: InfluxDB | Debian | Adding InfluxDB repository
      apt_repository:
        filename: influxdata_stable
        repo: "deb http://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        update_cache: yes
        state: present

    - name: InfluxDB | Debian | Installing
      apt:
        name:
          - influxdb
        state: present
      notify:
        - Handler | Restarting Influxdb

    # Workaround for https://community.influxdata.com/t/influxdb-1-8-7-will-not-start/20965
    - name: InfluxDB | Check existence of startscript
      stat:
        path: /usr/lib/influxdb/scripts/influxd-systemd-start.sh
      register: influxdb_startscript

    - name: InfluxDB | Workaround for startscript
      file:
        dest: /usr/lib/influxdb/scripts/influxd-systemd-start.sh
        mode: a+x
      when: influxdb_startscript.stat.exists
  when: ansible_os_family == "Debian"

- name: InfluxDB | Configuring | Modifing InfluxDB hostname
  replace:
    dest: /etc/influxdb/influxdb.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    backup: yes
  with_items:
    - { regexp: 'hostname = "localhost"', replace: 'hostname = "{{ cmk_influxdb_hostname }}"' }
    - { regexp: '  # bind-address = ":8086"', replace: '  bind-address = "{{ cmk_influx_bind_address }}"' }
  notify:
    - Handler | Restarting Influxdb

- meta: flush_handlers

- name: InfluxDB | Waiting for influxdb
  wait_for:
    port: 8086
    delay: 1

- name: InfluxDB | Configuring | Creating database nagflux
  influxdb_database:
    database_name: "{{ cmk_influxdb_nagflux_name }}"

- name: InfluxDB | InfluxDB | Configuring | Creating user {{ cmk_influxdb_nagflux_user }} for database nagflux
  influxdb_user:
    user_name: "{{ cmk_influxdb_nagflux_user }}"
    user_password: "{{ cmk_influxdb_nagflux_password }}"
  register: nagflux_user

- name: InfluxDB | Configuring | Grant all rights on database nagflux to {{ cmk_influxdb_nagflux_user }}
  command: 'influx -execute "GRANT ALL ON {{ cmk_influxdb_nagflux_name }} TO {{ cmk_influxdb_nagflux_user }}"'
  when: nagflux_user.changed
  tags: skip_ansible_lint
