---

- name: Checkmk | Installing
  apt:
    deb: "{{ cmk_url }}"
    state: present
  notify:
    - Restarting Apache2

- name: Checkmk | Configuring | Getting installed Checkmk sites
  command: "omd sites -b"
  register: cmk_sites
  changed_when: false

- name: Checkmk | Configuring | Creating Checkmk site {{ cmk_site_name }}
  command: "omd create {{ cmk_site_name }}"
  when: cmk_site_name not in cmk_sites.stdout_lines
  register: cmkdistro_created

- name: Checkmk | Configuring | Setting default user for site {{ cmk_site_name }}
  htpasswd:
    path: /opt/omd/sites/{{ cmk_site_name }}/etc/htpasswd
    name: "{{ cmk_default_user }}"
    password: "{{ cmk_default_password }}"
    owner: "{{ cmk_site_name }}"
    group: "{{ cmk_site_name }}"
    mode: 0640

- name: Checkmk | Configuring | Creating required directories for user {{ cmk_site_name }}
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ cmk_site_name }}"
    group: "{{ cmk_site_name }}"
    mode: 0775
  with_items:
    - /opt/omd/sites/{{ cmk_site_name }}/.ssh
    - /opt/omd/sites/{{ cmk_site_name }}/etc/ipmi-config

- name: Checkmk | Configuring | Getting Checkmk configuration details
  omdistro_facts:
    name: "{{ cmk_site_name }}"

- name: Checkmk | Configuring | Checkmk part 1
  command: omd config {{ cmk_site_name }} set {{ item.name }} {{ item.value }}
  when: omdistro_site_facts[item.name] is defined and omdistro_site_facts[item.name] != item.value
  with_items: "{{ cmk_site_config }}"
  #register: cmkdistro_config1
  notify:
    - Restarting Checkmk

- name: Checkmk | Configuring | Getting check_mk configuration details
  omdistro_facts:
    name: "{{ cmk_site_name }}"

- name: Checkmk | Configuring | Checkmk part 2
  command: omd config {{ cmk_site_name }} set {{ item.name }} {{ item.value }}
  when: omdistro_site_facts[item.name] is defined and omdistro_site_facts[item.name] != item.value
  with_items: "{{ cmk_site_config }}"
  #register: cmkdistro_config2
  notify:
    - Restarting Checkmk
