---

- name: Downloading nagflux
  get_url:
    url: https://github.com/Griesbacher/nagflux/releases/download/v{{ cmk_nagflux_version }}/nagflux
    dest: /usr/local/sbin/nagflux
    mode: 0755

- name: Creating nagflux config directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ cmk_site_name }}"
    group: "{{ cmk_site_name }}"
    mode: 0755
  with_items:
    - /etc/nagflux
    - /opt/omd/sites/{{ cmk_site_name }}/var/log/nagflux
    - /opt/omd/sites/{{ cmk_site_name }}/var/nagflux

- name: Configuring nagflux and nagflux systemd file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: nagflux_systemd.service.j2, dest: /etc/systemd/system/nagflux.service }
    - { src: nagflux_config.gcfg.j2, dest: /etc/nagflux/config.gcfg }
  notify:
    - Restarting Nagflux
