---

- name: Adding apt key for influxdb repo
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Adding InfluxDB repository
  apt_repository:
    filename: influxdata_stable
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    update_cache: no
    state: present

- name: Installing InfluxDB
  apt:
    name:
      - influxdb
      - influxdb-client
    state: present
  register: influxdb_installed

- name: Modifing InfluxDB hostname
  replace:
    dest: /etc/influxdb/influxdb.conf
    regexp: 'hostname = "localhost"'
    replace: 'hostname = "{{ ansible_hostname }}"'
    backup: yes
  register: influxdb_configchange

- name: (Re)starting Influxdb
  systemd:
    name: influxdb
    state: restarted
    enabled: true
  when: influxdb_installed.changed or influxdb_configchange.changed

- name: Creating Nagflux database
  influxdb_database:
    database_name: "{{ cmk_influxdb_nagflux_name }}"

- name: Creating user for the Nagflux database
  influxdb_user:
    user_name: "{{ cmk_influxdb_nagflux_user }}"
    user_password: "{{ cmk_influxdb_nagflux_password }}"
  register: nagflux_user

- name: Grant all rights on nagflux database to {{ cmk_influxdb_nagflux_user }}
  command: 'influx -execute "GRANT ALL ON {{ cmk_influxdb_nagflux_name }} TO {{ cmk_influxdb_nagflux_user }}"'
  when: nagflux_user.changed