---

# force mod-gearman-module from distribution repository
- name: mod-gearman | Installing | Templating apt preferences for Ubuntu
  blockinfile:
    path: /etc/apt/preferences
    create: yes
    owner: root
    group: root
    mode: 0644
    block: |
      Package: mod-gearman-module
      Pin: origin "archive.ubuntu.com"
      Pin-Priority: 999
    marker: "## {mark} ANSIBLE CHECKMK MANAGED BLOCK"
  when: ansible_distribution == "Ubuntu"

# mod-gearman-module from console repository requires naemon user / group...
# 1. chown: invalid user: 'naemon:naemon'
# 2. cp: cannot stat '/usr/share/doc/mod-gearman-module/examples/module.conf.gz': No such file or directory
#- name: Installing | Adding group naemon
#  group:
#    name: naemon
#    state: present

#- name: Installing | Adding user naemon
#  user:
#    name: naemon
#    group: naemon

- name: mod-gearman | Installing
  apt:
    name:
      - gearman
      - mod-gearman-module
      - mod-gearman-tools
      - libgearman-client-perl
      - libcrypt-rijndael-perl
      #- libgearman7
    state: present
    update_cache: yes

- name: mod-gearman | Configuring | Creating required mod-gearman directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ cmk_site_name }}"
    group: "{{ cmk_site_name }}"
    mode: 0755
  with_items:
    - /opt/omd/sites/{{ cmk_site_name }}/etc/mod-gearman
    - /opt/omd/sites/{{ cmk_site_name }}/var/log/gearman

- name: mod-gearman | Configuring | mod-gearman.cfg
  copy:
    dest: /opt/omd/sites/{{ cmk_site_name }}/etc/mod-gearman/mod-gearman.cfg
    owner: "{{ cmk_site_name }}"
    group: "{{ cmk_site_name }}"
    mode: 0644
    content: |
      #
      # Mod-Gearman NEB Module
      #
      event_broker_options=-1
      broker_module=/usr/lib/mod_gearman/mod_gearman.o config=/opt/omd/sites/{{ cmk_site_name }}/etc/mod-gearman/server.cfg

- name: mod-gearman | Configuring | mod-gearman secretfile
  copy:
    dest: /opt/omd/sites/{{ cmk_site_name }}/etc/mod-gearman/secret.key
    owner: "{{ cmk_site_name }}"
    group: "{{ cmk_site_name }}"
    mode: 0640
    content: |
      {{ cmk_mod_gearman_secret }}

- name: mod-gearman | Configuring | Linking mod-gearman.cfg to nagios.d
  file:
    src: /opt/omd/sites/{{ cmk_site_name }}/etc/mod-gearman/mod-gearman.cfg
    dest: /opt/omd/sites/{{ cmk_site_name }}/etc/nagios/nagios.d/mod-gearman.cfg
    owner: "{{ cmk_site_name }}"
    group: "{{ cmk_site_name }}"
    state: link

- name: mod-gearman | Configuring | mod-gearman server.cfg
  template:
    src: mod-gearman_server.cfg.j2
    dest: /opt/omd/sites/{{ cmk_site_name }}/etc/mod-gearman/server.cfg
    owner: "{{ cmk_site_name }}"
    group: "{{ cmk_site_name }}"
    mode: 0644

- name: mod-gearman | Configuring | pnp4nagios gearman worker systemd unit
  template:
    src: pnp4nagios_gearman.service.j2
    dest: /etc/systemd/system/pnp4nagios_gearman.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Handler | Restart pnp4nagios_gearman
