---

- name: Installing php module for apache
  apt:
    name: libapache2-mod-php
    state: present
    update_cache: yes
  notify:
    - Restarting Apache2

- name: Enabling php module for apache
  apache2_module:
    name: php7.2
    state: present
  notify:
    - Restarting Apache2

- name: Downloading and extracting histou
  unarchive:
    src: https://github.com/Griesbacher/histou/archive/v{{ cmk_histou_version }}.tar.gz
    dest: /opt
    owner: www-data
    group: www-data
    remote_src: yes
    creates: /opt/histou-{{ cmk_histou_version }}

- name: Configuring apache2 for histou
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: histou_apache2.conf.j2, dest: /etc/apache2/conf-available/histou.conf }
  notify:
    - Restarting Apache2

- name: Symlinking histou apache2 configuration
  file:
    src: /etc/apache2/conf-available/histou.conf
    dest: /etc/apache2/conf-enabled/histou.conf
    force: yes
    owner: root
    group: root
    state: link
  notify:
    - Restarting Apache2

- name: Check if histou.js symlink exist
  stat:
    path: /usr/share/grafana/public/dashboards/histou.js
  register: histou_symlink

- name: Symlinking histou.js
  file:
    src: /opt/histou-{{ cmk_histou_version }}/histou.js
    dest: /usr/share/grafana/public/dashboards/histou.js
    owner: root
    group: root
    state: link
  when: histou_symlink.stat.exists == False 