---
# histou requires php <= 7.1...Maybe someone can fix it?

- block:
    - name: PHP | Installing | Importing custom repository apt key
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x14aa40ec0831756756d7f66c4f4ea0aae5267a6c
        state: present

    - name: PHP | Installing | Adding custom repository
      apt_repository:
        filename: ondrej-ubuntu-php-{{ ansible_distribution_release }}.list
        repo: "deb http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_distribution_release }} main"
        update_cache: yes
        state: present

    - name: PHP | Installing | php module for apache
      apt:
        name: libapache2-mod-php7.1
        state: present
        update_cache: yes
      notify:
        - Handler | Restart Apache2

    - name: PHP | Configuring | Enabling php module for apache
      apache2_module:
        name: php7.1
        state: present
      notify:
        - Handler | Restart Apache2
  when: ansible_distribution == "Ubuntu"
