---

- name: Histou | Installing | Downloading and extracting histou
  unarchive:
    src: https://github.com/Griesbacher/histou/archive/v{{ cmk_histou_version }}.tar.gz
    dest: /opt
    owner: www-data
    group: www-data
    remote_src: yes
    creates: /opt/histou-{{ cmk_histou_version }}

- name: Histou | Configuring | root_url
  replace:
    path: /opt/histou-{{ cmk_histou_version }}/histou.js
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    owner: www-data
    group: www-data
    mode: 0664
    backup: yes
  with_items:
    - { regexp: '    var url = .*;', replace: "    var url = '{{ cmk_domain }}/histou/';" }

- name: Histou | Configuring | Enable histou.ini
  copy:
    src: /opt/histou-{{ cmk_histou_version }}/histou.ini.example
    dest: /opt/histou-{{ cmk_histou_version }}/histou.ini
    remote_src: true
    owner: www-data
    group: www-data
    mode: 0664

- block:
    - name: Histou | Configuring | apache2 for histou
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - { src: histou_apache2.conf.j2, dest: /etc/apache2/conf-available/histou.conf }
      notify:
        - Handler | Restart Apache2

    - name: Histou | Configuring | Symlinking histou apache2 configuration
      file:
        src: /etc/apache2/conf-available/histou.conf
        dest: /etc/apache2/conf-enabled/histou.conf
        force: yes
        owner: root
        group: root
        state: link
      notify:
        - Handler | Restart Apache2
  when: ansible_os_family == "Debian"

- name: Histou | Configuring | Check if histou.js symlink exist
  stat:
    path: /usr/share/grafana/public/dashboards/histou.js
  register: histou_symlink

- name: Histou | Configuring | Symlinking histou.js
  file:
    src: /opt/histou-{{ cmk_histou_version }}/histou.js
    dest: /usr/share/grafana/public/dashboards/histou.js
    owner: www-data
    group: www-data
    state: link
  when: not histou_symlink.stat.exists
