---

- name: Thruk | Installing
  apt:
    name: thruk
    state: present
    update_cache: yes

- name: Thruk | Configuring
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: www-data
    group: www-data
    mode: 0644
  with_items:
    - { src: thruk_config.conf.j2, dest: /etc/thruk/thruk_local.d/thruk_ansible.conf }
    - { src: thruk_menu.conf.j2, dest: /etc/thruk/menu_local.conf }
  notify:
    - Restarting Apache2
    - Restarting Thruk

- name: Thruk | Configuring | Checking Thruks htpasswd file
  stat:
    path: /etc/thruk/htpasswd
  register: thrukpasswd

- name: Thruk | Configuring | Symlinking Checkmks htpasswd with Thruks htpasswd
  file:
    src: /opt/omd/sites/{{ cmk_site_name }}/etc/htpasswd
    dest: /etc/thruk/htpasswd
    force: yes
    state: link
  when: not thrukpasswd.stat.islnk

- name: Thruk | Configuring | Give user {{ cmk_default_user }} authorized_for_admin permissions
  replace:
    path: /etc/thruk/cgi.cfg
    regexp: 'thrukadmin'
    replace: '{{ cmk_default_user }}'

- name: Thruk | Configuring | Setting permissions for Thruk configuration files
  file:
    path: /etc/thruk/cgi.cfg
    owner: www-data
    group: www-data

- name: Thruk | Configuring | Enable performance popup on hover
  copy:
    src: /etc/thruk/ssi/status-header.ssi.example
    dest: /etc/thruk/ssi/status-header.ssi
    remote_src: true
