---

- name: Installing Thruk
  apt:
    name: thruk
    state: present
    update_cache: yes

- name: Pre-configuring thruk
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: www-data
    group: www-data
  with_items:
    - { src: thruk_config.conf.j2, dest: /etc/thruk/thruk_local.d/thruk_ansible.conf }
    - { src: thruk_menu.conf.j2, dest: /etc/thruk/menu_local.conf }
  notify:
    - Starting Apache2
    - Restarting Thruk

- name: Symlink Check_MKs htpasswd with Thruks htpasswd
  file:
    src: /opt/omd/sites/{{ cmk_site_name }}/etc/htpasswd
    dest: /etc/thruk/htpasswd
    force: yes
    owner: www-data
    group: www-data
    state: link

- name: Setting permissions for Thruk configuration files
  file:
    path: /etc/thruk/cgi.cfg
    owner: www-data
    group: www-data