---

- name: Importing Grafana key for the grafana debian repository
  apt_key:
    url: "https://packages.grafana.com/gpg.key"

- name: Adding Grafana repository
  apt_repository:
    filename: grafana_stable
    repo: "deb http://packages.grafana.com/oss/deb stable main"
    update_cache: no
    state: present

- name: Installing Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes
  notify:
    - Restarting Grafana

- name: Setting Grafana default username
  replace:
    path: /etc/grafana/grafana.ini
    regexp: ';admin_user = .*'
    replace: 'admin_user = {{ cmk_default_user }}'

- name: Setting Grafana default password
  replace:
    path: /etc/grafana/grafana.ini
    regexp: ';admin_password = .*'
    replace: 'admin_password = {{ cmk_default_password }}'

- name: Setting Grafana root url
  replace:
    path: /etc/grafana/grafana.ini
    regexp: ';root_url = .*'
    replace: 'root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/'

- name: Bind Grafana to 127.0.0.1
  replace:
    path: /etc/grafana/grafana.ini
    regexp: ';http_addr ='
    replace: 'http_addr = 127.0.0.1'

- name: Configuring apache2 for grafana
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: grafana_apache2.conf.j2, dest: /etc/apache2/conf-available/grafana.conf }
  notify:
    - Restarting Apache2

- name: Symlinking grafana apache2 configuration
  file:
    src: /etc/apache2/conf-available/grafana.conf
    dest: /etc/apache2/conf-enabled/grafana.conf
    force: yes
    owner: root
    group: root
    state: link
  notify:
    - Restarting Apache2

- name: Creating the grafana provisioning folder
  file:
    path: /etc/grafana/provisioning/datasources/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Provisioning Nagflux database
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: grafana_datasource.yml.j2, dest: /etc/grafana/provisioning/datasources/influxdb-nagflux.yml }
  notify:
    - Restarting Grafana