---

- name: Installing requirements via apt
  apt:
    name: "{{ cmk_apt_requirements }}"
    state: present
    update_cache: yes

- name: Installing python requirements
  pip:
    name: "{{ cmk_python_requirements }}"

- name: Importing apt key for consol labs repo
  apt_key:
    id: F8C1CA08A57B9ED7
    keyserver: hkps://keys.gnupg.net

- name: Making sure the man8 folder exists
  file:
    path: /usr/share/man/man8
    state: directory
    mode: 0755