---

- name: Thruk | Including Debian tasks
  import_tasks: install_03_thruk_debian.yml
  when: ansible_os_family == "Debian"

- name: Thruk | Including RedHat tasks
  import_tasks: install_03_thruk_redhat.yml
  when: ansible_os_family == "RedHat"

- name: Thruk | Configuring | Checking Thruks htpasswd file
  stat:
    path: /etc/thruk/htpasswd
  register: thrukpasswd

- name: Thruk | Configuring | Symlinking Checkmks htpasswd with Thruks htpasswd
  file:
    src: /opt/omd/sites/{{ cmk_site_name }}/etc/htpasswd
    dest: /etc/thruk/htpasswd
    force: yes
    state: link
  when: not thrukpasswd.stat.islnk

- name: Thruk | Configuring | Disabling basic auth
  replace:
    path: /etc/thruk/thruk.conf
    regexp: '.*htpasswd = /etc/thruk/htpasswd'
    replace: '    #htpasswd = /etc/thruk/htpasswd'
  notify:
    - Handler | Restart Thruk

- name: Thruk | Configuring | Give user {{ cmk_default_user }} authorized_for_admin permissions
  replace:
    path: /etc/thruk/cgi.cfg
    regexp: 'thrukadmin'
    replace: '{{ cmk_default_user }}'
  notify:
    - Handler | Restart Thruk

- name: Thruk | Debian | Setting permissions for Thruk configuration files
  file:
    path: /etc/thruk/cgi.cfg
    owner: www-data
    group: www-data
  when: ansible_os_family == "Debian"

- name: Thruk | RedHat | Setting permissions for Thruk configuration files
  file:
    path: /etc/thruk/cgi.cfg
    owner: apache
    group: apache
  when: ansible_os_family == "RedHat"

- name: Thruk | Configuring | Enable performance popup on hover
  copy:
    src: /etc/thruk/ssi/status-header.ssi.example
    dest: /etc/thruk/ssi/status-header.ssi
    remote_src: true
    owner: root
    group: root
    mode: 0644
  notify:
    - Handler | Restart Thruk
