---

- name: Adding apt key for influxdb repo
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Adding InfluxDB repository
  apt_repository:
    filename: influxdata_stable
    repo: "deb http://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    update_cache: yes
    state: present

- name: Installing InfluxDB
  apt:
    name:
      - influxdb
    state: present
  notify:
    - Handler | Restarting Influxdb

- name: Modifing InfluxDB hostname
  replace:
    dest: /etc/influxdb/influxdb.conf
    regexp: 'hostname = "localhost"'
    replace: 'hostname = "{{ ansible_hostname }}"'
    backup: yes
  notify:
    - Handler | Restarting Influxdb

- meta: flush_handlers

- name: Waiting for influxdb
  wait_for:
    port: 8086
    delay: 1

- name: Creating Nagflux database
  influxdb_database:
    database_name: "{{ cmk_influxdb_nagflux_name }}"

- name: Creating user for the Nagflux database
  influxdb_user:
    user_name: "{{ cmk_influxdb_nagflux_user }}"
    user_password: "{{ cmk_influxdb_nagflux_password }}"
  register: nagflux_user

- name: Grant all rights on nagflux database to {{ cmk_influxdb_nagflux_user }}
  command: 'influx -execute "GRANT ALL ON {{ cmk_influxdb_nagflux_name }} TO {{ cmk_influxdb_nagflux_user }}"'
  when: nagflux_user.changed
  tags: skip_ansible_lint
