---

- name: Including basic setup tasks
  import_tasks: install_basic.yml
  tags: check_mk, thruk

- name: Including Ubuntu 18.04 tasks
  import_tasks: install_cmk_ubuntu1804.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'
  tags: check_mk

- name: Including Debian 9 tasks
  import_tasks: install_cmk_debian9.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '9'
  tags: check_mk

- name: Including Check_MK configuration tasks
  import_tasks: configure_cmk.yml
  tags: check_mk

- name: Including Thruk installation tasks
  import_tasks: install_thruk.yml
  tags: thruk

- name: Flush handlers
  meta: flush_handlers
  tags: check_mk, thruk

- name: Informational Output
  debug:
    msg:
      - ""
      - "Check_MK URL: http://{{ inventory_hostname }}/{{ cmk_site_name }}/check_mk"
      - "Thruk URL: http://{{ inventory_hostname }}/thruk"
      - "Default user: {{ cmk_default_user }}"
      - "Default password: {{ cmk_default_password }}"
  tags: check_mk, thruk