---

- name: Including basic setup tasks
  import_tasks: install_01_basic.yml
  tags: checkmk, thruk, influxdb, grafana, gearman

- name: Including Checkmk tasks
  import_tasks: install_02_cmk.yml
  tags: checkmk

- name: Including Thruk installation tasks
  import_tasks: install_03_thruk.yml
  tags: thruk

- name: Including InfluxDB installation tasks
  import_tasks: install_04_influxdb.yml
  tags: influxdb

- name: Including Grafana installation tasks
  import_tasks: install_05_grafana.yml
  tags: grafana

- name: Including Histou installation tasks
  import_tasks: install_06_histou.yml
  tags: histou

- name: Including Nagflux installation tasks
  import_tasks: install_07_nagflux.yml
  tags: nagflux

- name: Including mod_gearman installation tasks
  import_tasks: install_08_mod_gearman.yml
  tags: gearman

- name: Including php installation tasks
  import_tasks: install_09_php.yml
  tags: php

- name: Flush handlers
  meta: flush_handlers
  tags: checkmk, thruk, grafana, gearman

- name: Informational Output
  debug:
    msg:
      - ""
      - "Checkmk URL: http://{{ inventory_hostname }}/{{ cmk_site_name }}/check_mk"
      - "Thruk URL: http://{{ inventory_hostname }}/thruk"
      - "Grafana URL: http://{{ inventory_hostname }}/grafana"
      - "Default user: {{ cmk_default_user }}"
      - "Default password: {{ cmk_default_password }}"
  tags: checkmk, thruk, grafana
