---

- name: Including basic setup tasks
  import_tasks: install_01_basic.yml
  tags: check_mk, thruk

- name: Including Check_MK tasks
  import_tasks: install_02_cmk.yml
  tags: check_mk

- name: Including Thruk installation tasks
  import_tasks: install_03_thruk.yml
  tags: thruk

- name: Flush handlers
  meta: flush_handlers
  tags: check_mk, thruk

- name: Informational Output
  debug:
    msg:
      - ""
      - "Check_MK URL: http://{{ inventory_hostname }}/{{ cmk_site_name }}/check_mk"
      - "Thruk URL: http://{{ inventory_hostname }}/thruk"
      - "Default user: {{ cmk_default_user }}"
      - "Default password: {{ cmk_default_password }}"
  tags: check_mk, thruk