---

- name: Restarting Apache2
  systemd:
    name: apache2
    state: restarted
    enabled: true

- name: Restarting Check_MK
  command: omd restart {{ cmk_site_name }}

- name: Restarting Grafana
  systemd:
    name: grafana-server
    state: restarted
    enabled: true

- name: Restarting Nagflux
  systemd:
    name: nagflux
    state: restarted
    enabled: true

- name: Restarting Thruk
  systemd:
    name: thruk
    state: restarted
    enabled: true

- name: Handler | Restarting Influxdb
  systemd:
    name: influxdb
    state: restarted
    enabled: true
