---

- name: Starting Apache2
  systemd:
    name: apache2
    state: started
    enabled: true

- name: Restarting Check_MK
  command: omd restart {{ cmk_site_name }}

- name: Restarting Thruk
  systemd:
    name: thruk
    state: restarted
    enabled: true