---

- name: Handler | systemd daemon-reload
  systemd:
    daemon_reload: true

- name: Handler | Restart gearman-job-server
  systemd:
    name: gearman-job-server
    state: restarted
    enabled: true
    daemon_reload: true

- name: Handler | Restart Apache2
  systemd:
    name: apache2
    state: restarted
    enabled: true

- name: Handler | Restart Checkmk
  command: omd restart {{ cmk_site_name }}

- name: Handler | Restart Grafana
  systemd:
    name: grafana-server
    state: restarted
    enabled: true

- name: Handler | Restart Nagflux
  systemd:
    name: nagflux
    state: restarted
    enabled: true
    daemon_reload: true

- name: Handler | Restart Thruk
  systemd:
    name: thruk
    state: restarted
    enabled: true

- name: Handler | Restarting Influxdb
  systemd:
    name: influxdb
    state: restarted
    enabled: true
    daemon_reload: true

- name: Handler | Restart pnp4nagios_gearman
  systemd:
    name: pnp4nagios_gearman
    state: restarted
    enabled: true
    daemon_reload: true
