---

- name: Restarting Apache2
  service:
    name: apache2
    state: restarted
    enabled: true

- name: Restarting Checkmk
  command: omd restart {{ cmk_site_name }}

- name: Restarting Grafana
  service:
    name: grafana-server
    state: restarted
    enabled: true

- name: Restarting Nagflux
  service:
    name: nagflux
    state: restarted
    enabled: true

- name: Restarting Thruk
  service:
    name: thruk
    state: restarted
    enabled: true

- name: Handler | Restarting Influxdb
  systemd:
    name: influxdb
    state: restarted
    enabled: true

- name: Handler | Restart pnp4nagios_gearman
  systemd:
    name: pnp4nagios_gearman
    state: restarted
    enabled: true
