---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  export ANSIBLE_ROLES_PATH=${MOLECULE_PROJECT_DIRECTORY}/.
  yamllint -c .yamllint .
  ansible-lint -c .ansible-lint playbook.yml
platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    #command: ${MOLECULE_DOCKER_COMMAND:-""}
    command: "/lib/systemd/systemd"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  #config_options:
  #  defaults:
  #    interpreter_python: auto_silent
  #    callback_whitelist: profile_tasks, timer, yaml
    #connection:
    #  pipelining: true
  #env:
  #  PY_COLORS: 1
verifier:
  name: ansible
