---

- hosts: all

  tasks:
    - name: Preparing | Installing | Packages
      apt:
        name:
          - nano
          - net-tools
        update_cache: yes
        state: present
      when: ansible_os_family == "Debian"
