---

- hosts: all

  tasks:
    - name: Preparing | Debian | Packages
      apt:
        name:
          - nano
          - net-tools
        update_cache: yes
        state: present
      when: ansible_os_family == "Debian"

    - name: Preparing | RedHat | Packages
      yum:
        name:
          - nano
          - python3-libsemanage
        update_cache: yes
        state: present
      when: ansible_os_family == "RedHat"
